#!/bin/bash 
# Script to mirror an SVN project in git.

svn_url=$1

if [ -z "$1" ]; then
	echo "Usage: `basename $0` <url> (<localname>)"
	exit 1
fi
if [ -z "$2" ]; then
	basename_prefix=`basename $svn_url`
else
	basename_prefix="$2"
fi

#Make sure we have a trailing / on he URL
[[ $svn_url != */ ]] && 1="$svn_url"/

# Check if it looks like a standard repo
svn ls $svn_url > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo Does not appear to be a svn repository $svn_url
	exit 1
fi


gitsvn_basename="${basename_prefix}.git-svn"
git_basename="${basename_prefix}.git"

git_root=~git/repos
mirror_root=$git_root/mirror
local_version_root=$git_root/local-version
if [ ! -d $mirror_root ]; then
	mkdir -p $mirror_root
	echo Created mirror root: $mirror_root
fi
cd $mirror_root
if [ -d $gitsvn_basename ]; then
	echo Local folder already exists $gitsvn_basename
	exit 1
fi
if [ -d $git_basename ]; then
	echo Local folder already exists $git_basename
	exit 1
fi

svn ls ${svn_url}trunk > /dev/null 2>&1
if [ $? -eq 0 ]; then
	opts="-s"
fi


# Now bail if anything fails
set -e

git svn clone $opts $svn_url ${gitsvn_basename}-new

mv ${gitsvn_basename}-new $gitsvn_basename
pushd $gitsvn_basename
src_url=$(git config --get svn-remote.svn.url)
src_trunk=$(git config --get svn-remote.svn.fetch| sed 's/:.*//')
popd
git clone --bare $gitsvn_basename $git_basename
pushd $git_basename
# Add in an origin link
relative_path=`basename $gitsvn_basename`
echo -n "[remote \"origin\"]
  url = ../$relative_path
  fetch = +refs/remotes/*:refs/heads/*
" >> config
# Make trunk the default branch
echo "ref: refs/heads/trunk" > HEAD
touch git-daemon-export-ok
echo  "Clone from SVN of ${src_url}/${src_trunk}" > description
pushd refs/heads
ln -sf trunk master
popd
git fetch
popd
echo Updating project list....
update-project-list
