#!/bin/bash

# Exit if any of the commands fails.
set -e 

cd $HOME/repos/mirror
lockfile=.`basename $0`.lock

if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; 
then
   trap 'stat=$?; rm -f "$lockfile"; exit $stat' EXIT
   find . -mindepth 1 -maxdepth 2 -type d -name \*.git-svn | while read dir
   do
	   pushd $dir 
	   git svn fetch -q 
	   popd 
   done

   find . -mindepth 1 -maxdepth 2 -type d -name \*?.git| while read dir
   do
	   pushd $dir 
	   git fetch -q
	   git --bare update-server-info || exit 1
	   popd 
   done
else
   echo "Failed to acquire lockfile: $lockfile" 
   echo "Held by PID: $(cat $lockfile)"
fi 
